services:
  app:
    build: .
    env_file:
      - .env
    command: python app.py 
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD} 
      - DATABASE_NAME=${MYSQL_DATABASE} 
      - FLASK_ENV = ${FLASK_ENV} 
      - PAGERDUTY_API_KEY=${PAGERDUTY_API_KEY} 
      - REFRESH_DATA_RATE=${REFRESH_DATA_RATE}
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app